### ISSUE TITLE
My localtunnel URL often gets pointed to someone else's site after about 3 hrs

### ISSUE THREAD

**Issue by adjosh** [progrium/localtunnel#100]
I love the ease with which I was able to set up my localtunnel url. Thanks for a really awesome tool!
Is that URL generated by localtunnel not meant to be permanent? Or at least have a 24hr lifespan? How long is it supposed to last? I am trying to give clients access to review their project on my localhost. It will be a shame if by the time they are ready to click the link they are taken to some random strange project that isn't theirs!
Am I doing something wrong or are you still tinkering with stuff?
Please help!
Thanks.
Sarah
![thismorning](https://f.cloud.github.com/assets/2246466/378486/62a21e08-a541-11e2-8bf8-f20bd6672f26.png)
![thisafternoon](https://f.cloud.github.com/assets/2246466/378487/688cc19c-a541-11e2-9435-3b67efb6931f.png)

**Comment by progrium** [comment]
That version has reached EOL.
