### ISSUE TITLE
Get ERROR: exception, after loading a few pages

### ISSUE THREAD

**Issue by bathy** [progrium/localtunnel#103]
I installed localtunnel v2 on my ubuntu server with apache2 and I am tunneling through 80 port. I can see my website from the tunnel address with no problem.

However, after I browsed a few pages, I start to see unloaded pics first and then lost the connection completely. Then on the server side, it will show:

"ERROR exception" multiple times

Can you help me with this? My website can be found at pepchem.org and it is currently running on a small server. I was trying to move it to a bigger server inside my company.

Thanks in advance.

**Comment by progrium** [comment]
That version has reached EOL.
