### ISSUE TITLE
Having Problems Installing (Traceback included)

### ISSUE THREAD

**Issue by industriousind** [progrium/localtunnel#110]
I'm having problems installing localtunnel I'm sadly not very command-line savvy, so this might entirely be an issue on my end. I was originally trying to install localtunnel v1, but my RubyGems seem to need a "sudo install" to get them to install and I kept getting this error:

    ERROR:  Error installing localtunnel:
    	ERROR: Failed to build gem native extension.

So, I headed to your blog and found v2, and I tried "easy_installing" it, got this error:

    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the installation directory:
    
        [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-21087.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or the distutils default setting) was:
    
        /Library/Python/2.7/site-packages/
    
    Perhaps your account does not have write access to this directory?  If the installation directory is a system-owned directory, you may need to sign in as the administrator or "root" account.  If you do not have administrative access to this machine, you may wish to choose a different installation directory, preferably one that is listed in your PYTHONPATH environment variable.
    
    For information on other options, you may wish to consult the documentation at:
    
      http://peak.telecommunity.com/EasyInstall.html
    
    Please make the appropriate changes for your system and try again.

So, I "sudo easy-instaled" and this was the result:

    Searching for localtunnel
    Reading http://pypi.python.org/simple/localtunnel/
    Best match: localtunnel 0.6.1
    Downloading https://pypi.python.org/packages/2.7/l/localtunnel/localtunnel-0.6.1-py2.7.egg#md5=d40efb1bbd34e3d33ad4987c4cac6382
    Processing localtunnel-0.6.1-py2.7.egg
    Moving localtunnel-0.6.1-py2.7.egg to /Library/Python/2.7/site-packages
    Adding localtunnel 0.6.1 to easy-install.pth file
    Installing localtunneld script to /usr/local/bin
    Installing localtunnel-beta script to /usr/local/bin
    
    Installed /Library/Python/2.7/site-packages/localtunnel-0.6.1-py2.7.egg
    Processing dependencies for localtunnel
    Searching for argparse
    Reading http://pypi.python.org/simple/argparse/
    Best match: argparse 1.2.1
    Downloading http://argparse.googlecode.com/files/argparse-1.2.1.tar.gz#md5=2fbef8cb61e506c706957ab6e135840c
    Processing argparse-1.2.1.tar.gz
    Running argparse-1.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kZRKcF/argparse-1.2.1/egg-dist-tmp-DoZqxW
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.orig' found anywhere in distribution
    warning: no previously-included files matching '*.rej' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'env24'
    no previously-included directories found matching 'env25'
    no previously-included directories found matching 'env26'
    no previously-included directories found matching 'env27'
    zip_safe flag not set; analyzing archive contents...
    Adding argparse 1.2.1 to easy-install.pth file
    
    Installed /Library/Python/2.7/site-packages/argparse-1.2.1-py2.7.egg
    Searching for requests
    Reading http://pypi.python.org/simple/requests/
    Best match: requests 1.2.3
    Downloading https://pypi.python.org/packages/source/r/requests/requests-1.2.3.tar.gz#md5=adbd3f18445f7fe5e77f65c502e264fb
    Processing requests-1.2.3.tar.gz
    Running requests-1.2.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jMPQrZ/requests-1.2.3/egg-dist-tmp-dUN7_s
    Adding requests 1.2.3 to easy-install.pth file
    
    Installed /Library/Python/2.7/site-packages/requests-1.2.3-py2.7.egg
    Searching for eventlet
    Reading http://pypi.python.org/simple/eventlet/
    Reading http://eventlet.net
    Reading http://wiki.secondlife.com/wiki/Eventlet
    Best match: eventlet 0.13.0
    Downloading https://pypi.python.org/packages/source/e/eventlet/eventlet-0.13.0.tar.gz
    Processing eventlet-0.13.0.tar.gz
    Running eventlet-0.13.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-epwYI0/eventlet-0.13.0/egg-dist-tmp-TM09iZ
    Adding eventlet 0.13.0 to easy-install.pth file
    
    Installed /Library/Python/2.7/site-packages/eventlet-0.13.0-py2.7.egg
    Searching for greenlet>=0.3
    Reading http://pypi.python.org/simple/greenlet/
    Best match: greenlet 0.4.1
    Downloading https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.1.zip#md5=c2deda75bdda59c38cae12a77cc53adc
    Processing greenlet-0.4.1.zip
    Running greenlet-0.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0JZbNu/greenlet-0.4.1/egg-dist-tmp-fsn8nu
    unable to execute clang: No such file or directory
    unable to execute clang: No such file or directory
    error: Setup script exited with error: command 'clang' failed with exit status 1

I tried to run local tunnel-beta, thinking maybe it had just failed in a clean up or something, but this was my traceback:

    Traceback (most recent call last):
      File "/usr/local/bin/localtunnel-beta", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
        working_set.require(__requires__)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
        raise DistributionNotFound(req)  # XXX put more info here
    pkg_resources.DistributionNotFound: greenlet>=0.3

**Comment by progrium** [comment]
That version has reached EOL.
