### ISSUE TITLE
Character limit on url? Getting 502 error when url longer than 118 characters

### ISSUE THREAD

**Issue by jscheel** [progrium/localtunnel#80]
There appears to be some kind of character limit on urls. When I request a url that is 118 characters, everything works, when I request the same url, but 119 characters (change anything that will still point to the same file -- the subdomain, the query param name or value, etc)

__Works__ (118 characters)
```
http://*****.v2.localtunnel.com/assets/app/views/pop/editor/library/item/BackgroundImageEditorLibraryItemView.js?b=123
```
__Fails__ (119 characters)
```
http://*****.v2.localtunnel.com/assets/app/views/pop/editor/library/item/BackgroundImageEditorLibraryItemView.js?b=1234
```

**Comment by progrium** [comment]
That version has reached EOL.
