### ISSUE TITLE
Homebrew recipe

### ISSUE THREAD

**Issue by michaelrkn** [progrium/localtunnel#94]
Hey Jeff - what do you think about providing localtunnel as a Homebrew formula, instead of (or in addition to) installing with pip? I'm a Rubyist who loves localtunnel, and it would be great to be able to install it without having to install Python-specific stuff that I wouldn't otherwise need.

Thanks for your good work.

**Comment by progrium** [comment]
That Python version has reached EOL. There is a minimal Go version in master incubating. If there is demand, I'll produce binary releases that work on OS X and Linux.

**Comment by michaelrkn** [comment]
also [ngrok](https://ngrok.com/) is available through homebrew.

**Comment by mogul** [comment]
ngrok is now closed source. :(
