### ISSUE TITLE
ERROR: Unable to connect to service.

### ISSUE THREAD

**Issue by sodaridgelabs** [progrium/localtunnel#98]
I just installed localtunnel v2 on OS X, and I'm getting this error. Not sure why this is happening...as far as I know, there's nothing wrong with my internet connection. The older localtunnel was working fine just a few minutes ago.

**Comment by progrium** [comment]
That version has reached EOL. Ngrok is much more stable now. However there is also a minimal Go implementation in master for those that find that interesting.
