### ISSUE TITLE
i've installed argparse, still getting greenlet error

### ISSUE THREAD

**Issue by ckarbass** [progrium/localtunnel#99]
running 
sudo easy_install localtunnel

produces
Searching for localtunnel
Best match: localtunnel 0.5.8
Processing localtunnel-0.5.8-py2.6.egg
localtunnel 0.5.8 is already the active version in easy-install.pth
Installing localtunneld script to /usr/local/bin
Installing localtunnel-beta script to /usr/local/bin

Using /Library/Python/2.6/site-packages/localtunnel-0.5.8-py2.6.egg
Processing dependencies for localtunnel
Searching for greenlet>=0.3
Reading http://pypi.python.org/simple/greenlet/
Reading https://github.com/python-greenlet/greenlet
Reading http://bitbucket.org/ambroff/greenlet
Best match: greenlet 0.4.0
Downloading http://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.0.zip#md5=87887570082caadc08fb1f8671dbed71
Processing greenlet-0.4.0.zip
Running greenlet-0.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-WPpMyK/greenlet-0.4.0/egg-dist-tmp-oZHrqP
greenlet.c: In function ‘g_switch’:
greenlet.c:543: warning: ‘err’ may be used uninitialized in this function
/usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/as: assembler (/usr/bin/../libexec/gcc/darwin/ppc/as or /usr/bin/../local/libexec/gcc/darwin/ppc/as) for architecture ppc not installed
Installed assemblers are:
/usr/bin/../libexec/gcc/darwin/x86_64/as for architecture x86_64
/usr/bin/../libexec/gcc/darwin/i386/as for architecture i386
greenlet.c: In function ‘g_switch’:
greenlet.c:543: warning: ‘err’ may be used uninitialized in this function
greenlet.c: At top level:
greenlet.c:1711: fatal error: error writing to -: Broken pipe
compilation terminated.
greenlet.c: In function ‘g_switch’:
greenlet.c:543: warning: ‘err’ may be used uninitialized in this function
lipo: can't open input file: /var/tmp//ccKrOZ1b.out (No such file or directory)
error: Setup script exited with error: command 'gcc-4.2' failed with exit status 1

**Comment by progrium** [comment]
That version has reached EOL. If you haven't tried Ngrok, take a look. Otherwise, if there's demand, I'll set up binary releases for the new minimal Go implementation.
